@Kolibri_website.Server_HostAddress = http://localhost:5090

GET {{Kolibri_website.Server_HostAddress}}/(table|category)
Accept: application/json

###

POST {{Kolibri_website.Server_HostAddress}}/newcortege|delcortege|addcategory|delcategory|addquestion|addcustomer)
Accept: application/json
